version: "3.1"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easymed
      MYSQL_DATABASE: easymed
      MYSQL_USER: easymed
      MYSQL_PASSWORD: easymed
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql